// USE JQUERY
let jsdom = require("jsdom");
let dom = '...'
let { window } = new jsdom.JSDOM(dom);
const $ = require("jquery")(window);


container = $('<div>')
$(container).attr("class", "container col-12 d-flex flex-wrap justify-content-center");


// FUNCTION TO GENERATE HTML WITH USER INPUT
function outputHtml(employees) {
  
  // LOOP THROUGH EACH EMPLOYEE ENTRY AND GET NAME, ID, ROLE, ATTRIBUTE
  employees.forEach(employee  => {
  // DEFINE constIABLES
  var role = employee.getRole();
  var name = employee.name;
  var id = employee.id;
  var email = employee.email;
  if (role === "Manager") {
    var attr = employee.officeNum;
    var attrId = "OFFICE #: ";
  }
  if (role === "Engineer") {
    var attr = employee.gitHub;
    var attrId = "GITHUB: ";
  }
  if (role === "Intern") {
    var attr = employee.school;
    var attrId = "SCHOOL: ";
  }
  
  // EMPLOYEE MAIN CARD
  const card = $("<div>");
  $(card).attr("class", "card m-3 employee-card shadow-sm");
  $(card).attr("id", Math.floor(Math.random() * 100))
  $(container).append(card);

  // CARD HEADER
  const header = $("<div>");
  $(header).attr("class", "card-header name-role");
  const nameEl = $("<p>");
  const roleEl = $("<p>");
  $(nameEl).text(name);
  $(header).append(nameEl);
  $(roleEl).text(role);
  $(header).append(roleEl);
  $(card).append(header);

  // CARD BODY
  const body = $("<div>");
  $(body).attr("class", "card-body info");
  const bodyEl = $("<ul>");
  $(bodyEl).attr("class", "list-group list-group-flush");
  $(body).append(bodyEl);
  
  // EMPLOYEE ID
  const empId = $("<li>");
  $(empId).attr("class", "list-group-item");
  $(empId).text("ID: " + id);
  $(bodyEl).append(empId);
  
  // EMPLOYEE EMAIL
  const empEmail = $("<li>");
  $(empEmail).attr("class", "list-group-item");
  $(empEmail).text("EMAIL: " + email);
  $(bodyEl).append(empEmail);
  
  // EMPLOYEE OFFICENUM/GITHUB/SCHOOL
  const empAttr = $("<li>");
  $(empAttr).attr("class", "list-group-item");
  $(empAttr).text(attrId + attr);
  $(bodyEl).append(empAttr);

  $(card).append(body);
  
});
  
return `

<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="ie=edge">
<meta name="Description" content="Team Profile Page - Generated by TeamProfiler"/>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.6.0/css/bootstrap.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
<link rel="stylesheet" href="assets/css/style.css">
<title>Team Profile Page</title>
</head>
<body>

    <!-- HEADER -->
    <div class="jumbotron">
        <div class="container">
            <h1 class="display-3 text-center text-monospace">Team Members</h1>
            <p class="lead text-center text-monospace text-black-50">Breakdown of each team member and their role</p>
            <hr class="my-2">
            <p class="card-text text-center text-info font-weight-lighter text-monospace">Generated with TeamProfiler</p>
            </div>
    </div>
    
    <!-- CARDS -->
    ${container[0].outerHTML}

<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.slim.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.1/umd/popper.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.6.0/js/bootstrap.min.js"></script>
</body>
</html>

`;
}
module.exports = outputHtml;
